# Generated by Django 4.0.6 on 2022-07-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_alter_things_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='things.category'),
        ),
    ]
