# Generated by Django 4.0.6 on 2022-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_alter_things_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='things',
            options={'ordering': ['-done', 'deadline']},
        ),
        migrations.AddField(
            model_name='things',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
