# Generated by Django 4.0.6 on 2022-07-30 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0006_alter_things_options_things_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Things',
            new_name='Thing',
        ),
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['done', 'deadline']},
        ),
    ]
